-- MySQL Script generated by MySQL Workbench
-- Mon Dec 17 09:41:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema agrosrl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agrosrl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agrosrl` DEFAULT CHARACTER SET utf8 ;
USE `agrosrl` ;

-- -----------------------------------------------------
-- Table `agrosrl`.`estadocampo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrosrl`.`estadocampo` (
  `idestadoCampo` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idestadoCampo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrosrl`.`campo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrosrl`.`campo` (
  `idCampo` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `superficie` FLOAT NOT NULL,
  `idestadoCampo` INT(11) NOT NULL,
  PRIMARY KEY (`idCampo`, `idestadoCampo`),
  INDEX `fk_Campo_EstadoCampo1_idx` (`idestadoCampo` ASC),
  CONSTRAINT `fk_Campo_EstadoCampo1`
    FOREIGN KEY (`idestadoCampo`)
    REFERENCES `agrosrl`.`estadocampo` (`idestadoCampo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrosrl`.`cultivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrosrl`.`cultivo` (
  `idCultivo` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCultivo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrosrl`.`estadoproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrosrl`.`estadoproyecto` (
  `idEstadoProyecto` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstadoProyecto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrosrl`.`momento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrosrl`.`momento` (
  `idMomento` INT(11) NOT NULL,
  `momento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMomento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrosrl`.`tipolaboreo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrosrl`.`tipolaboreo` (
  `idTipoLaboreo` INT(11) NOT NULL,
  `labor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoLaboreo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrosrl`.`laboreocultiivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrosrl`.`laboreocultiivo` (
  `idLaboreoCultiivo` INT(11) NOT NULL,
  `orden` INT(11) NOT NULL,
  `idMomentoLaboreo` INT(11) NOT NULL,
  `idTipoLaboreo` INT(11) NOT NULL,
  `idCultivo` INT(11) NOT NULL,
  `idMomento` INT(11) NOT NULL,
  PRIMARY KEY (`idLaboreoCultiivo`, `idCultivo`, `idTipoLaboreo`, `idMomento`),
  INDEX `fk_LaboreoCultiivo_Cultivo1_idx` (`idCultivo` ASC),
  INDEX `fk_LaboreoCultiivo_TipoLaboreo1_idx` (`idTipoLaboreo` ASC),
  INDEX `fk_LaboreoCultiivo_Momento1_idx` (`idMomento` ASC),
  CONSTRAINT `fk_LaboreoCultiivo_Cultivo1`
    FOREIGN KEY (`idCultivo`)
    REFERENCES `agrosrl`.`cultivo` (`idCultivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LaboreoCultiivo_Momento1`
    FOREIGN KEY (`idMomento`)
    REFERENCES `agrosrl`.`momento` (`idMomento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LaboreoCultiivo_TipoLaboreo1`
    FOREIGN KEY (`idTipoLaboreo`)
    REFERENCES `agrosrl`.`tipolaboreo` (`idTipoLaboreo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrosrl`.`tiposuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrosrl`.`tiposuelo` (
  `id_tipo_suelo` INT(11) NOT NULL,
  `numero` VARCHAR(5) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_suelo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrosrl`.`lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrosrl`.`lote` (
  `idLote` INT(11) NOT NULL,
  `numero` INT(10) UNSIGNED NOT NULL,
  `superficie` FLOAT UNSIGNED NOT NULL,
  `idCampo` INT(11) NOT NULL,
  `idTipoSuelo` INT(11) NOT NULL,
  PRIMARY KEY (`idLote`, `idCampo`, `idTipoSuelo`),
  INDEX `fk_Lote_Campo_idx` (`idCampo` ASC),
  INDEX `fk_Lote_TipoSuelo1_idx` (`idTipoSuelo` ASC),
  CONSTRAINT `fk_Lote_Campo`
    FOREIGN KEY (`idCampo`)
    REFERENCES `agrosrl`.`campo` (`idCampo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lote_TipoSuelo1`
    FOREIGN KEY (`idTipoSuelo`)
    REFERENCES `agrosrl`.`tiposuelo` (`id_tipo_suelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrosrl`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrosrl`.`proyecto` (
  `idProyecto` INT(11) NOT NULL,
  `fechaInicio` DATE NULL DEFAULT NULL,
  `fechaFin` DATE NULL DEFAULT NULL,
  `idLote` INT(11) NOT NULL,
  `idCultivo` INT(11) NOT NULL,
  `idEstadoProyecto` INT(11) NOT NULL,
  PRIMARY KEY (`idProyecto`, `idLote`, `idCultivo`, `idEstadoProyecto`),
  INDEX `fk_Proyecto_Lote1_idx` (`idLote` ASC),
  INDEX `fk_Proyecto_Cultivo1_idx` (`idCultivo` ASC),
  INDEX `fk_Proyecto_EstadoProyecto1_idx` (`idEstadoProyecto` ASC),
  CONSTRAINT `fk_Proyecto_Cultivo1`
    FOREIGN KEY (`idCultivo`)
    REFERENCES `agrosrl`.`cultivo` (`idCultivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proyecto_EstadoProyecto1`
    FOREIGN KEY (`idEstadoProyecto`)
    REFERENCES `agrosrl`.`estadoproyecto` (`idEstadoProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proyecto_Lote1`
    FOREIGN KEY (`idLote`)
    REFERENCES `agrosrl`.`lote` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrosrl`.`tipolaboreo_has_proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrosrl`.`tipolaboreo_has_proyecto` (
  `idTipoLaboreo` INT(11) NOT NULL,
  `idProyecto` INT(11) NOT NULL,
  PRIMARY KEY (`idTipoLaboreo`, `idProyecto`),
  INDEX `fk_TipoLaboreo_has_Proyecto_Proyecto1_idx` (`idProyecto` ASC),
  INDEX `fk_TipoLaboreo_has_Proyecto_TipoLaboreo1_idx` (`idTipoLaboreo` ASC),
  CONSTRAINT `fk_TipoLaboreo_has_Proyecto_Proyecto1`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `agrosrl`.`proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TipoLaboreo_has_Proyecto_TipoLaboreo1`
    FOREIGN KEY (`idTipoLaboreo`)
    REFERENCES `agrosrl`.`tipolaboreo` (`idTipoLaboreo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrosrl`.`tiposuelo_has_cultivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrosrl`.`tiposuelo_has_cultivo` (
  `idTipoSuelo` INT(11) NOT NULL,
  `idCultivo` INT(11) NOT NULL,
  PRIMARY KEY (`idTipoSuelo`, `idCultivo`),
  INDEX `fk_TipoSuelo_has_Cultivo_Cultivo1_idx` (`idCultivo` ASC),
  INDEX `fk_TipoSuelo_has_Cultivo_TipoSuelo1_idx` (`idTipoSuelo` ASC),
  CONSTRAINT `fk_TipoSuelo_has_Cultivo_Cultivo1`
    FOREIGN KEY (`idCultivo`)
    REFERENCES `agrosrl`.`cultivo` (`idCultivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TipoSuelo_has_Cultivo_TipoSuelo1`
    FOREIGN KEY (`idTipoSuelo`)
    REFERENCES `agrosrl`.`tiposuelo` (`id_tipo_suelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
